import React from 'react';

export function TermsOfService() {
  return (
    <div className="p-8 max-w-3xl mx-auto">
      <h1 className="text-2xl font-bold mb-4">Terms of Service</h1>
      <p>Welcome to the Daily Workout Motivation app, operated by Lee Harrold. By using this app, you agree to the following terms:</p>
      
      <h2 className="text-xl font-semibold mt-4">1. Use of the App</h2>
      <p>This app is provided for fun and motivational purposes. You agree to use the app at your own risk and accept liability for any potential data breaches.</p>
      
      <h2 className="text-xl font-semibold mt-4">2. Content</h2>
      <p>The images sent to you are generated by an open-source, commercially licensed AI model. You may use these images freely, provided you credit Lee Harrold as the creator and the Daily Workout Motivation as the source.</p>
      
      <h2 className="text-xl font-semibold mt-4">3. Liability</h2>
      <p>You agree not to hold Lee Harrold liable for any issues arising from the use of this app. This includes, but is not limited to, data breaches, content accuracy, and app functionality.</p>
      
      <h2 className="text-xl font-semibold mt-4">4. Changes to Terms</h2>
      <p>Lee Harrold reserves the right to modify these terms at any time. Continued use of the app constitutes acceptance of the updated terms.</p>
    </div>
  );
} 