import React from 'react';

export const LEGAL_LAST_UPDATED = 'August 11, 2026';
export const LEGAL_CONTACT_EMAIL = 'halzinnia@gmail.com';

/**
 * The Terms of Service. Rendered both at /terms (the URL the iOS app links to,
 * and the one submitted to App Review) and inside the signup modal, so there is
 * only ever one version of this text.
 *
 * Section 4 is the auto-renewing subscription disclosure App Review requires of
 * any app selling an auto-renewable subscription; section 6 covers the
 * reference photo the visualiser can use.
 */
export function TermsOfService() {
  return (
    <div className="p-8 max-w-3xl mx-auto text-gray-800">
      <h1 className="text-2xl font-bold mb-1">Terms of Service</h1>
      <p className="text-sm text-gray-500 mb-6">Last updated {LEGAL_LAST_UPDATED}</p>

      <p>
        These terms govern your use of Cabo Coaches (the &ldquo;Service&rdquo;), which includes
        the <em>Coaches</em> iOS app and this website. The Service is operated by Lee Harrold
        (&ldquo;we&rdquo;, &ldquo;us&rdquo;). By creating an account or subscribing to a coach,
        you agree to these terms. If you do not agree, do not use the Service.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">1. What the Service is</h2>
      <p>
        Cabo Coaches is a roster of AI coaches across a range of disciplines &mdash; fitness and
        movement, music and creative practice, wellness, study and work habits, and others. Each
        coach has a persona built by a human creator, but the messages a coach sends you are
        generated by an AI model. Coaches message you in the app, and may reach out on their own
        schedule if you have allowed notifications.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">2. Not professional advice</h2>
      <p>
        Coaching content is for general information and motivation only. It is{' '}
        <strong>not</strong> medical, mental health, nutritional, financial, or other professional
        advice, and no coach is a licensed practitioner. Talk to a qualified professional before
        starting or changing an exercise, diet, or health regimen, and stop and seek help if you
        feel unwell. You take part at your own risk.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">3. Your account</h2>
      <p>
        You must be at least 13 years old (or the minimum age of digital consent where you live,
        if higher) to use the Service. You are responsible for what happens under your account.
        Do not use the Service to harass anyone, to solicit content involving minors, to
        impersonate another person, or to generate images of anyone other than yourself.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">
        4. Subscriptions, auto-renewal, and cancellation
      </h2>
      <p>
        Some coaches are free to try for a limited number of messages. Continuing beyond that
        requires a subscription to that coach. Subscriptions are per coach: subscribing to one
        coach does not subscribe you to any other.
      </p>
      <ul className="list-disc pl-6 mt-3 space-y-2">
        <li>
          <strong>What you get and for how long.</strong> A subscription unlocks unlimited
          messaging with that coach, coach-initiated check-ins, and the visualiser, for the
          subscription period. Subscriptions are monthly unless the coach&rsquo;s page states a
          different period.
        </li>
        <li>
          <strong>Price.</strong> The price and billing period for a coach are shown on that
          coach&rsquo;s page in the app before you confirm the purchase. Prices vary by coach and
          may differ by region.
        </li>
        <li>
          <strong>Payment.</strong> In the iOS app, payment is charged to your Apple ID account at
          confirmation of purchase. On this website, payment is charged to the card you provide,
          processed by Stripe.
        </li>
        <li>
          <strong>Auto-renewal.</strong> Subscriptions renew automatically. Your account is
          charged for renewal within 24 hours prior to the end of the current period, at the price
          then in effect, unless auto-renewal is turned off at least 24 hours before the end of
          the current period.
        </li>
        <li>
          <strong>Managing and cancelling.</strong> You can manage subscriptions and turn off
          auto-renewal in your Apple ID Account Settings after purchase (Settings &rarr; your
          name &rarr; Subscriptions, or from Settings inside the app). Cancelling stops the next
          renewal; the current period is not cancelled and, except where required by law, is not
          refunded. Refund requests for App Store purchases are handled by Apple, not by us.
        </li>
        <li>
          <strong>Free trials.</strong> Where a free trial is offered, any unused portion of it is
          forfeited when you purchase a subscription to that coach.
        </li>
        <li>
          <strong>Changes.</strong> We may change prices. A price change takes effect at your next
          renewal and never without notice; if you do not accept it, turn off auto-renewal before
          that renewal.
        </li>
      </ul>
      <p className="mt-3">
        Deleting the app does not cancel a subscription. Cancel it in your Apple ID Account
        Settings.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">5. AI-generated content</h2>
      <p>
        Coach messages and generated images are produced by AI models and can be wrong, generic,
        or unintentionally odd. Do not rely on them as fact. We do not guarantee that any
        particular coach, persona, or model remains available; coaches may be withdrawn by their
        creators or by us.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">6. Your photo and your likeness</h2>
      <p>
        The visualiser can generate images of the goal you are working toward. By default those
        images show no identifiable face. If &mdash; and only if &mdash; you upload a reference
        photo of yourself and grant likeness consent, we will use that photo to generate images
        that resemble you.
      </p>
      <ul className="list-disc pl-6 mt-3 space-y-2">
        <li>
          Upload only photos of yourself, that you have the right to use. Do not upload photos of
          other people, and never of a minor.
        </li>
        <li>
          You can withdraw likeness consent at any time in the app&rsquo;s settings. Withdrawing
          deletes the stored photo and reverts later generations to the faceless, scene-only mode.
        </li>
        <li>
          Generated images are for your personal use. Do not use them to imply an endorsement, or
          in a way that misrepresents a real person or event.
        </li>
      </ul>
      <p className="mt-3">
        How the photo is stored, who processes it, and how deletion works is described in the{' '}
        <a className="text-blue-600 underline" href="/privacy">
          Privacy Policy
        </a>
        .
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">7. Creator content</h2>
      <p>
        Creators who publish coaches keep ownership of the material they upload and grant us the
        licence needed to run their coach on the Service. You keep ownership of what you write to
        a coach, and grant us the licence needed to store it, show it back to you, and send it to
        our model providers so a coach can reply.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">8. Suspension and termination</h2>
      <p>
        We may suspend or close an account that breaks these terms. You may stop using the Service
        at any time; to have your data deleted, see the Privacy Policy.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">9. Disclaimers and liability</h2>
      <p>
        The Service is provided &ldquo;as is&rdquo;, without warranties of any kind to the extent
        the law allows. To the extent permitted by law, our total liability arising out of the
        Service is limited to the amount you paid us in the twelve months before the claim. Some
        jurisdictions do not allow these limits, in which case they apply only so far as they are
        permitted.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">10. Changes to these terms</h2>
      <p>
        We may update these terms. The date at the top shows the current version, and material
        changes will be surfaced in the app. Continuing to use the Service after a change means
        you accept the updated terms.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">11. Contact</h2>
      <p>
        Questions about these terms: <a className="text-blue-600 underline" href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a>.
      </p>
    </div>
  );
}
